version: "3.9"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

services:
  crypto-miner:
    container_name: crypto-miner
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    logging: *default-logging
    networks:
      - crypto-miner

networks:
  crypto-miner:
